### ISSUE TITLE
Very few edges estimated?

### ISSUE THREAD

**Issue by IrinaVanzhula** [SachaEpskamp/graphicalVAR#1]
Hi Sasha,

I am estimating n=1 networks using graphicalVAR. I have a 100 observations, 4 per day. Very few missing data and there is plenty of variability in the data. When I estimate the network, I get almost no edges for the directed network. Are only significance edges shown when I plot these? If so, is there a way to change significance level? What other reasons could there be for no edges showing? 
[Person2.pdf](https://github.com/SachaEpskamp/graphicalVAR/files/2522407/Person2.pdf)
[DH071.xlsx](https://github.com/SachaEpskamp/graphicalVAR/files/2522408/DH071.xlsx)

I attached the network image file. Code I am using is below. Thank you! 

n1 <-graphicalVAR(Data1, vars=Vars, dayvar=dayvar, beepvar=beepvar, gamma=0)
plot(n1, "PDC", labels = names)

**Comment by SachaEpskamp** [comment]
Hi,

You could consider not using the dayvar, as it costs you one quarter of your samples. If you don't use it, however, you are modeling the first response of the day as a function of the last response of the previous day, which is generally not recommended. You can also try to subset the number of variables. 

Best, Sacha
