### ISSUE TITLE
Individual network graph cut-off

### ISSUE THREAD

**Issue by IrinaVanzhula** [SachaEpskamp/graphicalVAR#2]
Hi Sasha,

This may be more qgraph question, but I am having trouble figuring out how to prevent self-loops being cut-off on individual network graphs. Even if I adjust the size of the image, the self-loops are partially cut-off if a node is close to the edge of the image. Also, I would like to be able to get rid of the label "Partially directed correlations" on the graph. I attached an example of an image and my code is below. Thank you! 

![Capture](https://user-images.githubusercontent.com/35053010/58222032-bb662f00-7ce2-11e9-8097-70c78194a8ad.JPG)

data2 <-graphicalVAR(Data1, vars=Vars, beepvar=beepvar, gamma=0)
plot(data2, "PCC", labels = names, fade=FALSE,
           vsize=10, legend=FALSE)
plot(data2, "PDC", labels = names, fade=FALSE,
           vsize=10, legend=FALSE)

**Comment by SachaEpskamp** [comment]
Hi Irina, Try using the arguments `titles = FALSE` and `mar = c(8, 8, 8, 8)` (or different values to change the margins).
