### ISSUE TITLE
Error when passing beepvar and dayvar

### ISSUE THREAD

**Issue by BenSeimon** [SachaEpskamp/graphicalVAR#5]
Hi Sacha, 

Firstly, your PhD dissertation is a fantastic introduction into the topic which I thoroughly enjoyed reading. 

I am trying to use the graphicalVAR package using ESM data. Both the code and csv file are attached (note that there is only one subject). However, I am encountering the following error when trying to run the code:

"Error in Beta_C(kappa, beta, X, Y, lambda_beta, lambda_mat, convergence,  : 
  Not compatible with requested type: [type=character; target=double]."

Please could you advise on how to overcome this issue? I have tried numerous different things (e.g. making the all the variables class 'double', including the id_var, beep_var and day_var as characters or doubles etc. but nothing seems to fix the error. 

Your help would be greatly appreciated!

Ben

[github_issue.zip](https://github.com/SachaEpskamp/graphicalVAR/files/8951650/github_issue.zip)

**Comment by SachaEpskamp** [comment]
Hi Ben,

Sorry for the late reply. Not sure if you still need a solution but here are some notes:

- The variables  'day_var', 'id_var' and 'beep_var' should not be in the `vars` argument; this argument should only indicate the variables that encode nodes in the networks. 
- `df = df[vars]` is not needed if you use `vars`
- There is no need to assign the arguments that have defaults (unless you want to change the defaults)
- The help file indicates which values you can assign. So for example `likelihood = c("unpenalized", "penalized")` indicates you can use `unpenalized` or `penalized` and that the first element is used as default. You cannot assign such an argument with a vector manually (the input is only one value not a vector).

This adjusted code works ok for me:

```
library('graphicalVAR')
library('dplyr')

df <- read.csv('ESM_data_github_issue.csv')

vars = c('Control', 'Sad', 'Intrusion', 'Encourage', 
         'FunThings', 'IgotThis', 'Alone', 'Thoughts', 
         'Appointments', 'Laying',
         'Out', 'Eaten', 'Avoid', 'Useful', 'Enjoy')


x <- graphicalVAR(df, 
             vars = vars,
             beepvar =  "beep_var", 
             dayvar = 'day_var')
```
